### ISSUE TITLE
Dimension exclusion list only account for loaded dimensions

### ISSUE THREAD

**Issue by Durpady** [LemADEC/UndergroundBiomesConstructs#1]
Title is a decent summary.  Despite IncludedDimensions=*, I am not seeing any UB Stone in the Twilight Forest, or in Mystcraft Ages.  I do have a few other mods that play with WorldGen (namely Botania, Thaumcraft, Biomes O' Plenty, and Tinker's Construct)... but none of those completely overhaul it, especially for other dimensions.  Is it possible that something in Underground Biomes isn't "hooked up" properly?

**Comment by LemADEC** [comment]
The configuration files only applies to newly created world. You need to check the worldSpecificConfig folder in your save if you want to change things up. There's also per-dimension settings, depending on what you've setup there.

**Comment by Durpady** [comment]
IncludedDimensions is set to * in WorldSpecificConfig, too.  I suppose I could create a whole new save file to make absolutely sure it's not some error on my end... I'll get back to you on that.

**Comment by LemADEC** [comment]
As explained in the configuration comments, if you set IncludedDimensions to *, then the mods relies on ExcludedDimensions, so you need to check both of those.

**Comment by Durpady** [comment]
Nope.  No dice.  I've never changed ExcludedDimensions from -1 and 1 (I did check though).  Brand new world, Twilight Forest is DIM7.  Before generating it, I checked the new world's WorldSpecificConfig, and IncludedDimensions was *, while ExcludedDimensions was -1,1.  Still only vanilla Stone.  Also I have DisableVanillaStoneVariants set to true, but they generated in DIM7 anyway... not sure if that's something that can be helped on your end though.

**Comment by Durpady** [comment]
In fact, just to be triple extra sure, I created a whole new Minecraft instance with just Twilight Forest and Underground Biomes installed (alongside their dependencies), and again performed all the previous checks.  Still no dice.  That tells me it's not something being done by another mod... unless that mod is Patchouli or Connected Textures.

**Comment by LemADEC** [comment]
When IncludedDimensions is set to *, the mod only account for currently loaded dimensions instead of accounting for all registered dimensions. You should be able to bypass that by changing IncludedDimensions with a explicit list of dimension ids.

**Comment by Durpady** [comment]
Hmm.  Well that would work easily enough for Twilight Forest, but what about Mystcraft?  I suppose I _could_ create a list of 10,000 dimension IDs...

I'll get back to you on testing it out with Twilight Forest.

**Comment by LemADEC** [comment]
It's unlikely you'll create so many MystCraft dimensions without severe diskspace usage issue...

**Comment by Durpady** [comment]
Alright, progress report.  Switching over to the IncludedDimensions list (and deleting data for DIM7 to regenerate it) _did_ cause UB stone to generate in the Twilight Forest.  That said, I've noticed some odd behavior.  It looks like UB doesn't replace Cobblestone Walls, Stairs or Stone Bricks, resulting in somewhat jarring structure generation in TF.  Also, it looks like TF generates Stalactites and Stalagmites, especially but not exclusively, in hollow hills, that UB only _sometimes_ replaces.
![2022-05-25_19 48 08](https://user-images.githubusercontent.com/10343498/170388060-713bcb98-156f-4787-ab1f-3bd1adb5e392.png)
![2022-05-25_19 49 28](https://user-images.githubusercontent.com/10343498/170388067-cb081aab-3787-4663-bae1-e3fa1fce6a1d.png)
![2022-05-25_19 49 56](https://user-images.githubusercontent.com/10343498/170388074-84617ebb-e077-432c-b1a5-7372ccb08589.png)
![2022-05-25_19 50 33](https://user-images.githubusercontent.com/10343498/170388078-8aef4475-ad65-4fd1-9376-344f4e03cd9d.png)

As for Mystcraft, I figured 10k would be enough to quash all but the most determined of "player shenanigans".  Perhaps I was mistaken, but 1k didn't strike me as enough.

**Comment by LemADEC** [comment]
each region file of 512x512 is typically 10 MB. If you only open the portal and don't really explore, in 1000 different dimensions, you're still using 10 GB of diskspace, without backups.

**Comment by LemADEC** [comment]
UBification applies to smooth stone, cobblestone, mossy cobblestone, monster eggs, yellow sand, clay, gravel, normal sandstone, smooth sandstone and a couple mod's specifics.  

I've added a few missing UBification :
* normal stone brick
* cracked stone brick (replaced with normal stone brick)
* mossy stone brick   (replaced with normal stone brick)
* cracked stone brick monster egg (not in the mod, replace with stone monster egg)
* chiseled sandstone
* half slab
* double slab
* normal cobblestone wall
* mossy cobblestone wall (replaced with normal cobblestone wall)

We'll still be missing due to some legacy issues in the mod :
* stairs

![image](https://user-images.githubusercontent.com/4776032/170590807-dbfa8bdc-3f6e-41f1-b44c-df5dcd1d5cd5.png)
