### ISSUE TITLE
UBC 1.12.2-1.3.12 Crashes Dedicated server at first start

### ISSUE THREAD

**Issue by kreezxil** [LemADEC/UndergroundBiomesConstructs#3]
UBC 1.12.2-1.3.12 Crashes Dedicated server at first start
while looking for client side classes.

https://gist.github.com/kreezxil/62d82ebf544c89f3a717852eec40725e

**Comment by LemADEC** [comment]
Log spam using a dead logger in a client side class, that's a serious case of bad luck
