### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by SenZ01** [LemADEC/UndergroundBiomesConstructs#4]
Exception in server tick loop
java.lang.NullPointerException

Description: I've been running around in singleplayer, jumped into a river and my game froze giving me this crashreport.
https://pastes.dev/5IarQAPXT3

Minecraft 1.12.2
Forge 14.23.5.2859
198 Mods
World: Singleplayer
Modversion: UndergroundBiomesConstructs-1.12-1.3.13
Optifine: Yes
Reproducing: I've tried to reproduce the problem but it seems to happen at random.

**Comment by JDLENL** [comment]
weirdly i just got the same error.

**Comment by SenZ01** [comment]
How many mods were you using?
i was just updating some mods in my pack and then that happened, very odd.

**Comment by LemADEC** [comment]
It's the worldgen bug with slab replacement. Previous fix was misplaced.
